### PR TITLE
Added support for Spine2D FFD

### PR DESCRIPTION
**Pull request by Kagamma**
This PR adds support for Spine2D free-form deformation.

A few notes:
- I am not aware of any cubic bezier variant of TCoordinateInterpolatorNode, so "curve" field is ignored for now.
- I also made a few changes to make Spine loader load weighted mesh correctly. The changes is quite ugly at the moment, but I think we will rewrite it once we add proper weighted mesh support so I will leave it like that.

Demo: https://www.youtube.com/watch?v=XDOkND_-LXU

### CODE REVIEW

**Comment by michaliskambi** [comment]
Cool, thank you! I'll test it soon and apply.

**Comment by michaliskambi** [comment]
@Kagamma I'm terribly sorry for not reviewing this PR yet -- I know it waits for a long time now, and I had it on my TODO list for this week, but I just didn't found time. (I was consumed by the viewport refactor mentioned in news on https://castle-engine.io/wp/2019/12/29/last-refactor-before-cge-7-0-release-say-hello-to-tcastleviewport-and-tcastlewindowbase-say-goodbye-to-tcastlescenemanager-and-tcastlewindow/ ).

I'll find time to review it and merge ASAP, hopefully tomorrow (Monday 30th Dec).

I know it often takes me too long to merge PRs (I try to do too many things at once, also in CGE:) ). Now and in the future: If merging any PR is blocking any of your work, please ping me and I'll prioritize myself better.

**Comment by Kagamma** [comment]
I removed the changes related to weighted mesh to avoid confusion, so only code related to FFD left.

On a side note, I try to build master branch version of view3dscene, using CGE master branch and notice Access Violation error when I try to load some of the Spine files I made for company. This is not happen for the release version of view3dscene on the website. Since I can't release those files which is company property I can only tell they were built using Spine 3.7.94, has quite complex animation (they are basically short cutscenes which last for several seconds), makes use of Spine latest features like clipping regions & weighted meshes.

**Comment by michaliskambi** [comment]
As for view3dscene error: 

- Does the problem occur too with snapshots, http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ ? These are build using latest (from GitHub) CGE + latest view3dscene source code, so I guess should have the same error.

- Does the problem occur also with CGE example `examples/3d_rendering_processing/view_3d_model_basic.lpr` ? It should, since it uses the same TCastleScene underneath as view3dscene. 

- There were a lot of changes since last release. So, without being able to reproduce, it will be hard for me to debug and fix it. So:

   1. I would ask for your help debugging it. Two things that come to mind:

      - Compile a debug version, and test it under a debugger (command-line GDB, or Lazarus). Is there a useful "Stack Trace" that shows where the Access Violation occurs? If the error is reproducible with view_3d_model_basic.lpr, then test it with view_3d_model_basic.lpr.

      - You can try using "bisection" to pinpoint the exact commit that caused it. It will be easiest to do if the error is reproducible with view_3d_model_basic.lpr, since then you only have one GIT repository to search for the bug. GIT has a nice "bisect" command to help with this process, https://git-scm.com/docs/git-bisect . If you can find an exact commit that caused the problem, there's a high chance that the problem with be obvious.

    2. Alternative: Is it possible to send the files privately to me (e.g. by email to `michalis.kambi@tutanota.com`)? For the sole purposes of reproducing and fixing this bug, of course. If your company is open to it, I can even sing a legal document (e.g. using DocuSign) to formally promise that I will really use these files *only* for the purpose of reproducing and fixing the problem, and that I will not redistribute these models to anyone else ever.

**Comment by Kagamma** [comment]
- Yes, the crash happens on both win32 and win64 snapshots.
- The bug happens on view_3d_model_basic example. Here is screenshot that shows stack trace: https://i.imgur.com/AmsY7MM.png
- I think it has something to do with slots. I will try to see if I could reproduce it on a simple Spine file.

**Comment by Kagamma** [comment]
I managed to create a Spine file that reproduce the bug. It start to crash when I add a clip region.

[test.zip](https://github.com/castle-engine/castle-engine/files/4014228/test.zip)

**Comment by michaliskambi** [comment]
Thank you! And again, sorry for taking so long to review this.

Merging. I'll commit a testcase of it too, and probably 2 improvements that I want to test first:

1. avoid duplicating the logic how `SkinName` -> determines the `CurrentSkin`.

2. I'm not sure whether it's correct that `ReadDeformTimelines` uses `Json.Names[0]` for slot name. I'll test it.

**Comment by michaliskambi** [comment]
I have committed small fixes:

- fix memory leaks: https://github.com/castle-engine/castle-engine/commit/c93d8550c5668fa513d2fe7d9296f555f85f5275
- fix Json.Names[0] usage: https://github.com/castle-engine/castle-engine/commit/d9ddcdaf861978a01fe0302eef2cfdd1700f0117
- do not calculate CurrentSkin twice (in case this logic will change in the future): https://github.com/castle-engine/castle-engine/commit/3c0bea95beb5a2b28eafb0d865cc0f3d7a3de282
- fix in case Offset is odd: https://github.com/castle-engine/castle-engine/commit/6b98901fd86d55d04b9d240e0ca676764f76b2aa

I made a testcase about this inside the demo-models repository, in https://github.com/castle-engine/demo-models/tree/master/spine/free_form_deformation .

I'll make a news about it soon, and I will use your video, if that's OK.

Thank you again! This is a very cool new feature!

**Comment by Kagamma** [comment]
Thanks for the fix! You can use my video I am ok with it.

**Pull request merged**
