### PR TITLE
Support for request body in CastleDownload (fpHttpClient)

### PR DESCRIPTION
**Pull request by phomm**
@michaliskambi , please point to the parts which are not covered and should be improved

### CODE REVIEW

**Comment by phomm** [comment]
FYI, had to manually update yml files, as my git tool didn't have ability to push them (some token issue), but in result I merged all changes from latest cge-master changes

**Comment by phomm** [comment]
Merged latest master changes

**Comment by michaliskambi** [comment]
Thanks for synching with master. I hope to finally get to addressing and merging this PR (and some others), now that I finally merged to CGE the big work (>400 commits) from `delphi-linux` branch :)

**Comment by michaliskambi** [comment]
Thank you and sorry for delay in addressing this!

I made tests and did a few modifications. See my commit with details in https://github.com/castle-engine/castle-engine/pull/558/commits/c8a660cd6fec9de1619049c45bc5935a3b462bdb . Practically, the most important is that I renamed it to HttpRequestBody and added an example. I also made really simple test in PHP to receive PUT and make sure it is OK -- https://github.com/castle-engine/cge-www/blob/master/htdocs/miscella/test_put.php ,

Merging!

**Pull request merged**
