### PR TITLE
Save castle editor window state

### PR DESCRIPTION
**Pull request by eugeneloza**
Save Castle Editor window state (maximized/minimized, width/height) and some internal parameters (three splitters positions) in UserConfig and load them upon reloading of the Form.

Fixes the first part of https://github.com/castle-engine/castle-engine/issues/216

### CODE REVIEW

**Comment by eugeneloza** [comment]
@michaliskambi also note that here I used the "default values" from current LFM files - which for me (1366x768) go a bit off screen, we might want to adjust those to something small - visible on all monitors or define them based on `Screen.Height` and `Screen.Width`.

**Comment by michaliskambi** [comment]
- I think we store too many values . Do we need to store both `Width` and `ClientWidth` in many cases? Seems like only one of them should be necessary. If really both must be saved/restored then setting their order must be carefully documented, as one of them sets also the other.

- Do not store window state as Minimized or Fullscreen, it would be unexpected to restore in minimized state. Store only normal vs maximized.

- When restoring, make sure to not restore at all if these values were not recorded in settings file. E.g. use a boolean like `ProjectForm_Saved`. We have already a good default behavior on all screen sizes thanks to LCL form settings, we do not want to break them. Neither hardcoding them nor basing on `Screen` should be necessary here, the default behavior is just good already.

- When restoring, check that form doesn't go offscreen. In case user e.g. changes monitors.

**Comment by eugeneloza** [comment]
All seems to be fixed! :)

**Review by michaliskambi — APPROVED** [review]
All looks cool, thank you!

**Pull request merged**
