### PR TITLE
Physics: Fix first castle transform position update.

### PR DESCRIPTION
**Pull request by and3md**
Little fix for first Castle Transform position update by `TransformationFromKraft`. After `TRigidBody.InitializeTransform` Kraft shape transform was not set properly. That makes strange effects before first physics step. See code comment for more info. Tested in my game ;)

### CODE REVIEW

**Comment by michaliskambi** [comment]
Makes sense. 

But I would like to reproduce the problem to be sure I can always confirm it's still fixed :) I tried adding

```
SceneManager.TimeScale := 0.0;
```

to ApplicationInitialize in examples/physics/physics_3d_demo/gameinitialize.pas , but I do not see a bug. 

Can you describe what I would need to do (in examples/physics/physics_3d_demo/ or other demo) to see the problem?

(BTW, if I exit the physics_3d_demo then, it reports an error -- `EAssertionFailed: Second deinitialization! (castletransform_physics.inc, line 530)`. )

**Comment by and3md** [comment]
I will check physics_3d_demo and try to make a simple example with this bug.

**Comment by and3md** [comment]
In physics_3d_demo when level is destroyed first `TRigidBody` of a box is destroyed next the box (TCastleTransform) itself. Then the FRigidBody pointer is incorrect. So in TRigidBody.Destroy we need set TCastleTransform.FRigidBody to nil.

**Comment by and3md** [comment]
OK, I added space to stop time and R to restart in collision example. Just press space to pause and then R. The position of new plane will be incorrect (without https://github.com/castle-engine/castle-engine/pull/120/commits/e1f6063ddbfbb14026e8c9598d1ae3e5286e930c). When time is on this is hard to see.

**Comment by michaliskambi** [comment]
Thank you for both fixes! Tested and merged :) I extended the comments a bit -- my memory is short, so I need to document everything :)

**Pull request merged**
