### PR TITLE
New Flag for WMEraseBkgnd to avoid flicker

### PR DESCRIPTION
**Pull request by ProHolz**
published the VCL Mouse Events

### CODE REVIEW

**Review by michaliskambi — CHANGES_REQUESTED** [review]
Thank you! I had in TODO to deal with this flicker. Indeed handling WM_ERASEBKGND is what is needed, our TCastleWindow on WinAPI also does it.

I would request one change: let's remove the `EraseBackGround` property and field, and just do it always. There doesn't seem to be much point in making this (ignoring WM_ERASEBKGND) be optional and so we don't want to support the option of `EraseBackGround = true`.

I.e. `WMEraseBkgnd` should just unconditionally do 

```pascal
procedure TCastleControl.WMEraseBkgnd(var Message: TWMEraseBkgnd);
begin
  Message.Result := 1;
end;
```

**Comment by ProHolz** [comment]
For me this will work, I can change it no problem

**Comment by ProHolz** [comment]
property EraseBackGround removed

**Review by michaliskambi — APPROVED** [review]
Thank you!

**Pull request merged**
