### PR TITLE
Quick patches: Load color property + fix typo in type name (rel. to Tiled maps)

### PR DESCRIPTION
**Pull request by Free-Pascal-meets-SDL-Website**
Patch 1) Set color property on loading of Tiled maps.
Patch 2) Fix typo in type name of Tiled object primitives.

### CODE REVIEW

**Review by michaliskambi — APPROVED** [review]
Thank you!

**Comment by michaliskambi** [comment]
TTileObjectPrimitive -> TTiledObjectPrimitive also required additional change to fix compilation, I did it :)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Oh, I missed that. For my test compilation it worked well. On examination I found that it is because this part of code is in an Inc-file, on adding it to the project inspector, it raises a compilation error here, too. Thanks! :)

**Comment by michaliskambi** [comment]
> Oh, I missed that. For my test compilation it worked well. On examination I found that it is because this part of code is in an Inc-file, on adding it to the project inspector, it raises a compilation error here, too. Thanks! :)

That's because our `castle_base.lpk` was missing the explicit reference to `ui/opengl/castletiledmap_map.inc` file. This is now fixed by an internal tool that automatically scans all CGE packages and reports if they miss any file (.pas, .inc) that is present on disk. I just added this tool in commit https://github.com/castle-engine/castle-engine/commit/3c7614b5c2dfd6bf9f3073264abdbb85e6b29237 , and fixed all our LPK packages to be valid.

So, this problem should not return :)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Sounds great! I will definitivly check this out. :)

**Pull request merged**
