### PR TITLE
Remove CastleRandom from the Engine, Tests and Examples

### PR DESCRIPTION
**Pull request by eugeneloza**
A remake of https://github.com/castle-engine/castle-engine/tree/98-maybe-make-castlerandom-an-asset ---- but that branch is in a massive merge conflict, so it seemed faster just to remake the cleanup.

Note, I avoided large diffs by autosaving LPIs and LPKs. The numeration of the included units gets broken, but it doesn't seem to hurt anything, those files seem to load without any issues in Lazarus and tests show no related errors as far as I can see.

The CastleRandom itself is now extracted into https://github.com/castle-engine/castle-random

### CODE REVIEW

**Comment by eugeneloza** [comment]
> EDOMChildElementError: Child "Item50" not found

Ok, so it didn't break Lazarus but has broken CGE validation. I'll fix it.

**Comment by eugeneloza** [comment]
Ok, seems to be finally fixed

**Review by michaliskambi — APPROVED** [review]
Everything looks cool, thank you! I'll merge as soon as automated tests confirm it's OK :)

**Comment by eugeneloza** [comment]
> I didn't know that Lazarus tolerates "holes" in indexes of these items.

Yeah, what I did was open LPI/LPK in Lazarus and save them manually and then... clean-up dozens of unrelated added lines in GitHub Desktop :)

I'm afraid some information was still lost (in Tests LPKs, they had unit names), but Lazarus sorted and mixed units so there was no way to recover the lost lines. I believe they didn't contain anything crucial though.

**Comment by eugeneloza** [comment]
Oh, so it actually passed! I've got two mails that it failed. Maybe for previous two commits.

**Comment by michaliskambi** [comment]
Thank you, merged!

> Oh, so it actually passed! I've got two mails that it failed. Maybe for previous two commits.

GitHub Actions mails like to be the bearers of the bad news :) They send emails on commits that failed, but not for ones that succeeded.

**Pull request merged**
