### PR TITLE
Make CastleXMLUtils.URLWriteXML capable of gzip compression

### PR DESCRIPTION
**Pull request by eugeneloza**
Added ability to cast stream options through CastleXMLUtils.URLWriteXML (with aim at gzip compression)

### CODE REVIEW

**Comment by michaliskambi** [comment]
Thank you!

P.S. I may change the "Options: TStreamOptions" to "Options: TSaveStreamOptions" parameter, on both URLSaveStream and URLWriteXML. The other flag of TStreamOptions (soForceMemoryStream) doesn't do anything on them, at least for now, so it may be confusing.

**Comment by michaliskambi** [comment]
>  I may change the "Options: TStreamOptions" to "Options: TSaveStreamOptions" parameter

Yes, done:) So, to use gzip compression when saving, use `URLWriteXML(..., [ssoGzip);` (`ssoGzip` enum, not `soGzip`).

**Comment by eugeneloza** [comment]
Thanks a lot! I'll pull it right now.

**Comment by eugeneloza** [comment]
Now I had to remake reading procedures :)  I get an exception:
`EXMLReadError: In 'stream:' (line 1 pos 2): Invalid character in input stream`
It looks like URLReadXML provides empty options to Stream := Download(URL, []);
I've fixed it in the commit, but as usually I'm not sure if I did it all correctly :) Works perfectly for my tasks.
https://github.com/eugeneloza/castle-engine/commit/a7923a03c42fbf94705d7a8f5dce5a2bd21eca1b

**Comment by michaliskambi** [comment]
> It looks like URLReadXML provides empty options to Stream := Download(URL, []);

I think you meant this commit: https://github.com/eugeneloza/castle-engine/commit/2377d1b7af1893f7ecb83d45772cc0b88cd3b1f3

Yes, this is consistent and nice, I will happily merge it:) Can you submit a pull request? You can submit a pull request with everything you committed to https://github.com/eugeneloza/castle-engine/ , including work on #50 and #51 .

**Pull request merged**
