### PR TITLE
a few fixes to documentation

### PR DESCRIPTION
**Pull request by eugeneloza**
Mostly a "test" fix for documentation.
See https://sourceforge.net/p/castle-engine/discussion/general/thread/d5e053ef/#116d

### CODE REVIEW

**Comment by michaliskambi** [comment]
Hm, you have based your changes on the old version of the code. At a time when I announced the documentation improvements, I did many changes around these parts -- in particular, 

- all nodes have now at least 1-sentence comment,
- x3d_navigation.inc is now x3dnodes_standard_navigation.inc.
- Also, the PasDoc error in x3dnodes.pas is now fixed (although differently).

Can you please redo your changes relative to the latest engine state? Sorry for the mess, I usually don't do such large changes... well, but this time I did it:)

The GitHub pull request shows the information whether there are conflicts, or not.

As for the documentation style, I still have some nitpicking:)

> { returns true if camera view orientation is known }

Always use full, English sentences, that start with upper letter and end with a dot. So it's better to write:

> { Returns true if camera view orientation is known. }

Also, the first sentence (up to the first dot, see https://github.com/pasdoc/pasdoc/wiki/AutoAbstractOption ) is automatically picked up as the "abstract" by PasDoc. It should be concise, and not repeat anything obvious. So it's better to write:

> { Returns if camera view orientation is known. }

or even better

> { Is the camera view orientation known. }

(BTW, do not be tempted to end it with "?", end it with ".", as it's not a question -- it's a description of the value. Also, Pasdoc's --auto-abstract expects the sentence to end with ".", not "?")

So, avoid words that do not actually enhance the meaning, especially in that first sentence. Instead of "Returns blah.", you can usually say just "Blah." ("Returns the game state." -> "Game state.")

Instead of "Controls blah.", "Determines blah.", ... you can also usually (but, admittedly, not always) say "Blah."

I wrote some ideas about it on castle-engine/doc/pasdoc/README.txt long time ago. These are not mine, actually -- I was loosely basing on javadoc standards, http://www.oracle.com/technetwork/articles/java/index-137868.html , although I also probably deviated from them too:)

**Comment by eugeneloza** [comment]
Thanks a lot, I'll try to rewrite everything which is needed.
Now it's time for me to learn how to "resolve" the branch conflicts :)

**Comment by eugeneloza** [comment]
Finally I've resolved the formal conflicts between branches :)
So I can start working on fixing the content now.

**Comment by eugeneloza** [comment]
Aww... The diff says it reverted the complete file :) So for now its just castleRandom comments fixes. I'll re-create a new pull request then.

**Pull request closed without merging**
