### PR TITLE
Set WalkNavigation MouseDragMode to rotate in deprecated library when automatic touch interface is set

### PR DESCRIPTION
**Pull request by janadamec1**
Related to removing ControlMouseDragMode in commit https://github.com/castle-engine/castle-engine/commit/6ff0c154548e361d166a4a9616c99bd0485d00cf

We need to address this in the deprecated library. The AutoNavigationViewport used there, so it seems the sufficient solution is to set WalkNavigation MouseDragMode when CGE_SetUserInterface(true) is called to set the automatic touch interface.

### CODE REVIEW

**Review by michaliskambi — CHANGES_REQUESTED** [review]
It seems more future-proof to introduce another routine, like `CGE_SetMouseDragMode(...)`, to control the `Viewport.InternalWalkNavigation.MouseDragMode` . This could take an enum that allows to use all 3 values of [TMouseDragMode](https://castle-engine.io/apidoc/html/CastleCameras.html#TMouseDragMode).

In effect, just like for CGE Pascal API the ` TCastleTouchNavigation`  and `TCastleWalkNavigation.MouseDragMode` are independent, also in the library the `CGE_SetUserInterface(...)` and `CGE_SetMouseDragMode(...)` would be independent.

**Comment by michaliskambi** [comment]
The new version means that setting `TouchNavigation.AutoWalkTouchInterface` and `Viewport.InternalWalkNavigation.MouseDragMode` happen together. This means you hardcode the logic "which `AutoWalkTouchInterface` value best corresponds to which `MouseDragMode`" (when you do `if (nValue = 2 {ecgetciCtlWalkDragRotate}) ... then`). So this means that library C API (unlike Pascal API) would "combine" the 2 things which we want to keep independent: 

- what touch controls are present (the 0/1/2 gizmos in viewport corners) 

- and what happens when you drag on the viewport.

I say to make it all independent in library C API, just like it is in Pascal API. And rename stuff in C API to be as consistent with Pascal API as possible. Advantages: 

1. This will give the C library user maximum flexibility. For the same reason as we made them independent in Pascal API, they should be independent in library C API.

2. It will make the library code more straightforward, so easier to maintain. One C library "concept" should control the corresponding one Pascal API concept. The enums, routines exposed by library should match as closely as possible the Pascal API, to keep things simple.

Disadvantage: I realize this means we break C API backward-compatibility. I would say we should do this -- we need to have things consistent to maintain the library easily. You are likely the only user of this API right now, so I hope you can adjust your application. 

So

1. One thing should control `TouchNavigation.AutoWalkTouchInterface` (and nothing more).

    Maybe this should be `CGE_SetVariableInt(ecgevarWalkTouchCtl)` or maybe separate API call `CGE_SetAutoWalkTouchInterface`. I admit I prefer more new `CGE_SetAutoWalkTouchInterface`, not extending the `CGE_SetVariableInt`, but I'm fine either way.

    And maybe rename `ecgevarWalkTouchCtl` to `ecgevarAutoWalkTouchInterface`. Make it obvious what C API concept corresponds to what Pascal API concept.
   
    The allowed enums should correspond, in names, to allowed enums of Pascal. We have this in Pascal:

    ```
    TTouchInterface = (
      tiNone,
      tiWalk,
      tiWalkRotate,
      tiFlyWalk,
      tiPan
    );
    ```

    So I would say to rename the C enums from

    ```
    enum ECgeTouchCtlInterface
    {
      ecgetciNone              = 0,
      ecgetciCtlWalkCtlRotate  = 1,
      ecgetciCtlWalkDragRotate = 2,
      etciCtlFlyCtlWalkDragRotate = 3,
      etciCtlPanXYDragRotate   = 4,
    };
    ````
 
    to something like this ->

    ```
    enum ECgeTouchInterface
    {
      ecgetiNone       = 0,
      ecgetiWalk       = 1,
      ecgetiWalkRotate = 2,
      ecgetiFlyWalk    = 3,
      ecgetiPan        = 4,
    };
    ```
    
2. Introduce an indepenedent way to influence `Viewport.InternalWalkNavigation.MouseDragMode`. Either `CGE_SetMouseDragMode` or `CGE_SetVariableInt(ecgevarMouseDragMode)`.

4. And keep, as we have now, an independent way to set boolean `TouchNavigation.AutoTouchInterface`. This is now called `CGE_SetUserInterface`, I would be OK to rename it (since we rename things anyway) to `CGE_SetAutoTouchInterface`.

I realize that I propose a bigger, breaking change than you. I still think it's a good direction -- we break things today, but we have a smooth way forward, the library code is easy to maintain because it is obvious "what maps to what". The resulting library code should be straightforward, if C API things correspond in obvious way to Pascal API.

**Comment by janadamec1** [comment]
OK, I hope, everything is done

**Review by michaliskambi — APPROVED** [review]
Thank you -- this looks perfect for me now :) Merging!

**Pull request merged**
